### ISSUE TITLE
Show battery percentage

### ISSUE THREAD

**Issue by yahlowgrin** [PanicMan/Pebble-Casio-WV58DE#1]
Hi, it will be great if you can add a battery percentage (eg, 80%) with a tiny font right under the battery icon, so that we can decide when to charge the watch, rather than guessing from the icon itself.

**Comment by PanicMan** [comment]
Sorry, I'm lean on the original style of the casio watch an there is just an battery icon. I'm sure after some charging cycles every one knows when it's time to charge... ;)
