### ISSUE TITLE
Support local configuration w/o need for internet connection

### ISSUE THREAD

**Issue by arnowelzel** [PanicMan/Pebble-Casio-WV58DE#4]
The watch face allows to configure some settings - nice.

But the configuration needs a working internet connection to load the HTML file via HTTP just to show a configuration page - not so nice.

One solution: https://github.com/pebble/clay

It would be nice if this watch face would use this as well to support configuration without the need for online access to a webserver.

Oh - and this is also the recommended way now by Pebble: https://developer.pebble.com/guides/user-interfaces/app-configuration/

**Comment by PanicMan** [comment]
Ok, thanks. Have to look on this, but really no time atm... :(

**Comment by arnowelzel** [comment]
No worries - Pebble is dead anyway :-( Thanks for the good watch face.

**Comment by PanicMan** [comment]
Not yet. My Pebble is still working!

2017-07-03 16:50 GMT+02:00 Arno Welzel <notifications@github.com>:
