### ISSUE TITLE
API Key Expired

### ISSUE THREAD

**Issue by antoinepetty** [PanicMan/Pebble-Casio-WV58DE#6]
Can't fetch weather data from API with current key - replacing this key fixes the issue
https://github.com/PanicMan/Pebble-Casio-WV58DE/blob/8789f3fbe89025b3d4bc0c97365e33d6423910d2/src/pkjs/js/pebble-js-app.js#L101

p.s. thanks for making this watchface, I've been using it for years :)

**Comment by PanicMan** [comment]
Hello, thanks for reporting it... As I have no Pebble anymore you could try fork the code, add your own api key there, it's free, then it should work again. I'm very busy at the moment, I will try to change the configuration page, that you can enter there your own api key, but I can only test this with the emulator...

**Comment by antoinepetty** [comment]
No worries, I had some help editing the .pbz file to replace the key with my own which worked well (and didn't need rebuilding).
I'm happy to test it if you get around to changing the config page :)
